config/routes.rb
Bfsa::Application.routes.draw do
  root "pages#home"
  get "membership" => "pages#membership"
  get "scholarship" => "pages#scholarship"
  get "mentoring" => "pages#mentoring"
  get "calendar" => "pages#calendar"
  get "photos" => "pages#photos"
  get "contact" => "pages#contact"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def membership
  end

  def scholarship
  end

  def mentoring
  end

  def calendar
  end

  def photos
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-inverse navnar-bottom" role="navigation">
  <div class="container-fluid">
    <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><span class=" glyphicon glyphicon-copyright-mark"></span>Black Faculty and Staff Association</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->xx
  </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Black Faculty and Staff Association</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Membership", membership_path %></li>
        <li><%= link_to "Scholarship", scholarship_path %></li>
        <li><%= link_to "Mentoring", mentoring_path %></li>
        <li><%= link_to "Calendar", calendar_path %></li>
        <li><%= link_to "Photos", photos_path %></li>
        <li><%= link_to "Contact Us", contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BFSA</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<%= yield %>
</div>
<div id="space"></div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/calendar.html.erb
<h1>Pages#calendar</h1>
<p>Find me in app/views/pages/calendar.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div id="jumbg">
<div class="jumbotron">
	
	<h2 id="name">Black Faculty and Staff Association</h2>
	<p>
		The Black Faculty and Staff Association (BFSA) at CSU Dominguez Hills is a community of professionals who share a common ethnic bond or interest in the African-American experience in academia.
	</p>
	<p>
		United by a common goal to encourage and exemplify personal, professional and academic excellence, we aim to serve as leaders and role models and be a network of support for each other and the students this university serves.
	</p>
	<p>
		<h3 id="mem">Membership is open to everyone! </h3>
	<p>
</div>
<div id="botm">
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="http://images2.snapfish.com/232323232%7Ffp53838%3Enu=3549%3E347%3E254%3EWSNRCG=32;73559%3C9345nu0mrj" alt="..." class="center" width="900" height="400">
      <div class="carousel-caption">
      	<h1></h1>
      </div>
    </div>
    <div class="item">
      <img src="http://www.csudh.edu/bfsa/Santa%20Anita%20-%20Group%20Pic.jpeg" alt="..." class="center">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="http://www.csudh.edu/bfsa/BFSA%202010%20choir%202.jpeg" alt="..." class="center">
      <div class="carousel-caption">
        ...
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
</div>

app/views/pages/membership.html.erb
<h1>Pages#membership</h1>
<p>Find me in app/views/pages/membership.html.erb</p>

app/views/pages/mentoring.html.erb
<h1>Pages#mentoring</h1>
<p>Find me in app/views/pages/mentoring.html.erb</p>

app/views/pages/photos.html.erb
<h1>Pages#photos</h1>
<p>Find me in app/views/pages/photos.html.erb</p>

app/views/pages/scholarship.html.erb
<h1>Pages#scholarship</h1>
<p>Find me in app/views/pages/scholarship.html.erb</p>